/* Pure calculation functions. Annual returns are effective, net assumptions. */
(function(root){
const rate = annual => Math.pow(1+annual/100,1/12)-1;
function future(initial,monthly,years,annual){const n=Math.round(years*12),r=rate(annual);return Math.abs(r)<1e-12?initial+monthly*n:initial*Math.pow(1+r,n)+monthly*Math.expm1(n*Math.log1p(r))/r;}
function monthlyContribution(target,initial,months,annual){if(months<=0)return null;const r=rate(annual),growth=Math.pow(1+r,months),remaining=target-initial*growth;if(remaining<=0)return 0;const contributionFactor=Math.abs(r)<1e-12?months:Math.expm1(months*Math.log1p(r))/r;return remaining/contributionFactor;}
function projectCpfAt55({age,oa,sa,grossMonthlySalary,owCeiling=8000,frs=220400}){if(age>55)throw new Error('This CPF projection is designed for ages 55 and below.');const shares=[{max:35,oa:.6217,sa:.1621},{max:45,oa:.5677,sa:.1891},{max:50,oa:.5136,sa:.2162},{max:55,oa:.4055,sa:.3108}],months=Math.max(0,Math.round((55-age)*12)),monthlyOaRate=Math.pow(1.025,1/12)-1,monthlySaRate=Math.pow(1.04,1/12)-1,contribution=Math.min(grossMonthlySalary,owCeiling)*.37;let projectedOa=oa,projectedSa=sa;for(let month=0;month<months;month++){const memberAge=age+month/12,share=shares.find(band=>memberAge<band.max)||shares[shares.length-1];projectedOa=projectedOa*(1+monthlyOaRate)+contribution*share.oa;projectedSa=projectedSa*(1+monthlySaRate)+contribution*share.sa;}const totalBeforeRa=projectedOa+projectedSa,raAt55=Math.min(totalBeforeRa,frs);return{months,oaAt55:projectedOa,saAt55:projectedSa,totalBeforeRa,raAt55,oaAfterRa:Math.max(0,totalBeforeRa-frs),saAfterRa:0,raGap:Math.max(0,frs-raAt55),frs};}
function retirementCapitalWithPayout({spend,retire,end,post,inflation,payoutAt65,payoutEscalation=0}){const months=Math.max(0,Math.round((end-retire)*12)),monthlyReturn=Math.pow(1+post/100,1/12)-1,monthlyInflation=Math.pow(1+inflation/100,1/12)-1;let presentValue=0;for(let month=1;month<=months;month++){const yearsFromRetirement=(month-1)/12,ageAtMonth=retire+yearsFromRetirement,spending=spend*Math.pow(1+monthlyInflation,month-1),payout=ageAtMonth<65?0:payoutAt65*Math.pow(1+payoutEscalation/100,ageAtMonth-65);presentValue+=(spending-payout)/Math.pow(1+monthlyReturn,month);}return{capital:Math.max(0,presentValue),incomeSurplusValue:Math.max(0,-presentValue),months};}
function retirement(x){const years=x.retire-x.age,n=x.end-x.retire,infl=1+x.inflation/100;const spending=x.spend*Math.pow(infl,years),gap=Math.max(0,spending-x.income);const realMonthly=Math.pow((1+x.post/100)/infl,1/12)-1;const months=n*12;const capital=Math.abs(realMonthly)<1e-12?gap*months:gap*(-Math.expm1(-months*Math.log1p(realMonthly)))/realMonthly;const projected=future(x.saved,x.monthly,years,x.pre),shortfall=Math.max(0,capital-projected);const factor=future(0,1,years,x.pre);return {years,spending,gap,capital,projected,shortfall,extra:factor?shortfall/factor:null};}
const api={future,monthlyContribution,projectCpfAt55,retirement,retirementCapitalWithPayout};if(typeof module!=='undefined')module.exports=api;root.PlanningMath=api;
})(typeof window!=='undefined'?window:globalThis);
